#![cfg_attr(coverage_nightly, coverage(off))]
// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub(crate) mod sql_types {
    /// The `device_algorithm` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "device_algorithm"))]
    pub struct DeviceAlgorithm;
}

diesel::table! {
    /// Representation of the `magic_link_requests` table.
    ///
    /// (Automatically generated by Diesel.)
    magic_link_requests (id) {
        /// The `id` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Uuid>,
        /// The `email` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `code` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Bytea,
        /// The `expires_at` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `mfa_recovery_codes` table.
    ///
    /// (Automatically generated by Diesel.)
    mfa_recovery_codes (id) {
        /// The `id` column of the `mfa_recovery_codes` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `mfa_recovery_codes` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `code_hash` column of the `mfa_recovery_codes` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        code_hash -> Varchar,
    }
}

diesel::table! {
    /// Representation of the `mfa_totp_credentials` table.
    ///
    /// (Automatically generated by Diesel.)
    mfa_totp_credentials (id) {
        /// The `id` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `name` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Nullable<Varchar>,
        /// The `secret` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        secret -> Bytea,
        /// The `last_used_at` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `mfa_totp_reg_sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    mfa_totp_reg_sessions (user_id) {
        /// The `user_id` column of the `mfa_totp_reg_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `secret` column of the `mfa_totp_reg_sessions` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        secret -> Bytea,
        /// The `expires_at` column of the `mfa_totp_reg_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `mfa_webauthn_auth_sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    mfa_webauthn_auth_sessions (user_id) {
        /// The `user_id` column of the `mfa_webauthn_auth_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `state` column of the `mfa_webauthn_auth_sessions` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        state -> Jsonb,
        /// The `expires_at` column of the `mfa_webauthn_auth_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `mfa_webauthn_credentials` table.
    ///
    /// (Automatically generated by Diesel.)
    mfa_webauthn_credentials (id) {
        /// The `id` column of the `mfa_webauthn_credentials` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `mfa_webauthn_credentials` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `name` column of the `mfa_webauthn_credentials` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Nullable<Varchar>,
        /// The `credential_id` column of the `mfa_webauthn_credentials` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        credential_id -> Bytea,
        /// The `credential` column of the `mfa_webauthn_credentials` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        credential -> Jsonb,
        /// The `counter` column of the `mfa_webauthn_credentials` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        counter -> Nullable<Int8>,
        /// The `last_used_at` column of the `mfa_webauthn_credentials` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `mfa_webauthn_reg_sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    mfa_webauthn_reg_sessions (user_id) {
        /// The `user_id` column of the `mfa_webauthn_reg_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `state` column of the `mfa_webauthn_reg_sessions` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        state -> Jsonb,
        /// The `expires_at` column of the `mfa_webauthn_reg_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `new_user_email_requests` table.
    ///
    /// (Automatically generated by Diesel.)
    new_user_email_requests (id) {
        /// The `id` column of the `new_user_email_requests` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `new_user_email_requests` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `email` column of the `new_user_email_requests` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `code` column of the `new_user_email_requests` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Bytea,
        /// The `expires_at` column of the `new_user_email_requests` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `organization_invitations` table.
    ///
    /// (Automatically generated by Diesel.)
    organization_invitations (id) {
        /// The `id` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Uuid>,
        /// The `organization_id` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `email` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `invited_by_id` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        invited_by_id -> Uuid,
        /// The `expires_at` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `organization_member_policies` table.
    ///
    /// (Automatically generated by Diesel.)
    organization_member_policies (organization_id, user_id, policy_id) {
        /// The `organization_id` column of the `organization_member_policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `user_id` column of the `organization_member_policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `policy_id` column of the `organization_member_policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        policy_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `organization_members` table.
    ///
    /// (Automatically generated by Diesel.)
    organization_members (organization_id, user_id) {
        /// The `organization_id` column of the `organization_members` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `user_id` column of the `organization_members` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `invited_by_id` column of the `organization_members` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        invited_by_id -> Nullable<Uuid>,
        /// The `inline_policy` column of the `organization_members` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        inline_policy -> Nullable<Varchar>,
        /// The `created_at` column of the `organization_members` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `organizations` table.
    ///
    /// (Automatically generated by Diesel.)
    organizations (id) {
        /// The `id` column of the `organizations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `google_customer_id` column of the `organizations` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        google_customer_id -> Nullable<Varchar>,
        /// The `google_hosted_domain` column of the `organizations` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        google_hosted_domain -> Nullable<Varchar>,
        /// The `name` column of the `organizations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `owner_id` column of the `organizations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        owner_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `policies` table.
    ///
    /// (Automatically generated by Diesel.)
    policies (id) {
        /// The `id` column of the `policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `organization_id` column of the `policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `project_id` column of the `policies` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        project_id -> Nullable<Uuid>,
        /// The `name` column of the `policies` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `description` column of the `policies` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `policy` column of the `policies` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        policy -> Varchar,
    }
}

diesel::table! {
    /// Representation of the `projects` table.
    ///
    /// (Automatically generated by Diesel.)
    projects (id) {
        /// The `id` column of the `projects` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `projects` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `organization_id` column of the `projects` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `role_policies` table.
    ///
    /// (Automatically generated by Diesel.)
    role_policies (role_id, policy_id) {
        /// The `role_id` column of the `role_policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        role_id -> Uuid,
        /// The `policy_id` column of the `role_policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        policy_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `roles` table.
    ///
    /// (Automatically generated by Diesel.)
    roles (id) {
        /// The `id` column of the `roles` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `organization_id` column of the `roles` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `name` column of the `roles` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `description` column of the `roles` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `inline_policy` column of the `roles` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        inline_policy -> Nullable<Varchar>,
    }
}

diesel::table! {
    /// Representation of the `service_account_policies` table.
    ///
    /// (Automatically generated by Diesel.)
    service_account_policies (service_account_id, policy_id) {
        /// The `service_account_id` column of the `service_account_policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        service_account_id -> Uuid,
        /// The `policy_id` column of the `service_account_policies` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        policy_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `service_account_tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    service_account_tokens (id) {
        /// The `id` column of the `service_account_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `active` column of the `service_account_tokens` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        active -> Bool,
        /// The `service_account_id` column of the `service_account_tokens` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        service_account_id -> Uuid,
        /// The `token` column of the `service_account_tokens` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        token -> Bytea,
        /// The `inline_policy` column of the `service_account_tokens` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        inline_policy -> Nullable<Varchar>,
        /// The `expires_at` column of the `service_account_tokens` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `service_accounts` table.
    ///
    /// (Automatically generated by Diesel.)
    service_accounts (id) {
        /// The `id` column of the `service_accounts` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `service_accounts` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `organization_id` column of the `service_accounts` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `project_id` column of the `service_accounts` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        project_id -> Nullable<Uuid>,
        /// The `inline_policy` column of the `service_accounts` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        inline_policy -> Nullable<Varchar>,
    }
}

diesel::table! {
    /// Representation of the `user_emails` table.
    ///
    /// (Automatically generated by Diesel.)
    user_emails (email) {
        /// The `email` column of the `user_emails` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `user_id` column of the `user_emails` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `created_at` column of the `user_emails` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `user_google_accounts` table.
    ///
    /// (Automatically generated by Diesel.)
    user_google_accounts (sub) {
        /// The `sub` column of the `user_google_accounts` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        sub -> Varchar,
        /// The `user_id` column of the `user_google_accounts` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `access_token` column of the `user_google_accounts` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        access_token -> Varchar,
        /// The `access_token_expires_at` column of the `user_google_accounts` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        access_token_expires_at -> Timestamptz,
        /// The `created_at` column of the `user_google_accounts` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `user_session_requests` table.
    ///
    /// (Automatically generated by Diesel.)
    user_session_requests (id) {
        /// The `id` column of the `user_session_requests` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `device_name` column of the `user_session_requests` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        device_name -> Varchar,
        /// The `device_ip` column of the `user_session_requests` table.
        ///
        /// Its SQL type is `Inet`.
        ///
        /// (Automatically generated by Diesel.)
        device_ip -> Inet,
        /// The `code` column of the `user_session_requests` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 6]
        code -> Varchar,
        /// The `approved_by` column of the `user_session_requests` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        approved_by -> Nullable<Uuid>,
        /// The `expires_at` column of the `user_session_requests` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::DeviceAlgorithm;

    /// Representation of the `user_sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    user_sessions (user_id, device_fingerprint) {
        /// The `user_id` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `device_fingerprint` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        device_fingerprint -> Bytea,
        /// The `device_algorithm` column of the `user_sessions` table.
        ///
        /// Its SQL type is `DeviceAlgorithm`.
        ///
        /// (Automatically generated by Diesel.)
        device_algorithm -> DeviceAlgorithm,
        /// The `device_pk_data` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        device_pk_data -> Bytea,
        /// The `last_used_at` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Timestamptz,
        /// The `last_ip` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Inet`.
        ///
        /// (Automatically generated by Diesel.)
        last_ip -> Inet,
        /// The `token_id` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        token_id -> Nullable<Uuid>,
        /// The `token` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Nullable<Bytea>`.
        ///
        /// (Automatically generated by Diesel.)
        token -> Nullable<Bytea>,
        /// The `token_expires_at` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        token_expires_at -> Nullable<Timestamptz>,
        /// The `expires_at` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
        /// The `mfa_pending` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        mfa_pending -> Bool,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `preferred_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        preferred_name -> Nullable<Varchar>,
        /// The `first_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        first_name -> Nullable<Varchar>,
        /// The `last_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        last_name -> Nullable<Varchar>,
        /// The `password_hash` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        password_hash -> Nullable<Varchar>,
        /// The `primary_email` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        primary_email -> Nullable<Varchar>,
        /// The `avatar_url` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        avatar_url -> Nullable<Varchar>,
    }
}

diesel::joinable!(magic_link_requests -> users (user_id));
diesel::joinable!(mfa_recovery_codes -> users (user_id));
diesel::joinable!(mfa_totp_credentials -> users (user_id));
diesel::joinable!(mfa_totp_reg_sessions -> users (user_id));
diesel::joinable!(mfa_webauthn_auth_sessions -> users (user_id));
diesel::joinable!(mfa_webauthn_credentials -> users (user_id));
diesel::joinable!(mfa_webauthn_reg_sessions -> users (user_id));
diesel::joinable!(new_user_email_requests -> users (user_id));
diesel::joinable!(organization_invitations -> organizations (organization_id));
diesel::joinable!(organization_member_policies -> policies (policy_id));
diesel::joinable!(organization_members -> organizations (organization_id));
diesel::joinable!(organizations -> users (owner_id));
diesel::joinable!(policies -> organizations (organization_id));
diesel::joinable!(policies -> projects (project_id));
diesel::joinable!(projects -> organizations (organization_id));
diesel::joinable!(role_policies -> policies (policy_id));
diesel::joinable!(role_policies -> roles (role_id));
diesel::joinable!(roles -> organizations (organization_id));
diesel::joinable!(service_account_policies -> policies (policy_id));
diesel::joinable!(service_account_policies -> service_accounts (service_account_id));
diesel::joinable!(service_account_tokens -> service_accounts (service_account_id));
diesel::joinable!(service_accounts -> organizations (organization_id));
diesel::joinable!(service_accounts -> projects (project_id));
diesel::joinable!(user_google_accounts -> users (user_id));
diesel::joinable!(user_session_requests -> users (approved_by));
diesel::joinable!(user_sessions -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    magic_link_requests,
    mfa_recovery_codes,
    mfa_totp_credentials,
    mfa_totp_reg_sessions,
    mfa_webauthn_auth_sessions,
    mfa_webauthn_credentials,
    mfa_webauthn_reg_sessions,
    new_user_email_requests,
    organization_invitations,
    organization_member_policies,
    organization_members,
    organizations,
    policies,
    projects,
    role_policies,
    roles,
    service_account_policies,
    service_account_tokens,
    service_accounts,
    user_emails,
    user_google_accounts,
    user_session_requests,
    user_sessions,
    users,
);
